# Site settings
title: Coded Silk Labs
email: your-email@example.com # Update with your actual email
description: >- # this means to ignore newlines until "baseurl:"
  The official online platform for the Universal Equation Framework, showcasing
  extensive research, documents, and a blog, with advanced dynamic features and a focus on user-friendly customization.
baseurl: "" # Keep this empty for root domain hosting
url: "https://codedsilklabs.github.io" # Your live GitHub Pages URL
permalink: /:categories/:title/ # Example permalink structure

# Build settings
markdown: kramdown
# theme: minima # DELETE or COMMENT OUT this line as we're using a custom theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag # Recommended for SEO

# Custom variables (for easy access in layouts)
colors:
  background: "#1a1a2e" # Deep, rich dark background
  mint: "#66ffcc"       # Pale neon mint green
  turquoise: "#00e6e6"   # Turquoise accent
  text_light: "#e0e0e0"  #_
